# Generated by Django 3.0 on 2020-11-09 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201108_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Gratitude_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('gratitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gratitude')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_like', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', through='api.Comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratitude',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='gratitude_likes', through='api.Gratitude_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
