# Generated by Django 3.0 on 2020-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gratitude_like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
