# Generated by Django 3.0 on 2020-11-12 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201110_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gratitude',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Gratitude'),
        ),
        migrations.AddField(
            model_name='gratitude',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
