# Generated by Django 3.0 on 2020-11-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201112_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gratitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gratitude'),
        ),
    ]
