# Generated by Django 3.0 on 2020-11-17 18:27

import api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201113_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user.upload_path),
        ),
    ]
