# Generated by Django 3.0 on 2020-11-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
